### ISSUE TITLE
Lookup as autocomplete with back-end call

### ISSUE THREAD

**Issue by arjendeblok** [aurelia-ui-toolkits/aurelia-mdc-web#16]
I have implemented a lookup as an autocomplete as described in #2
 
But now I have a problem when I want to use a variable in the page view model for doing a back-end call.
Because the call to the `options` function is made from the `MdcLookup` component, the this pointer in my method in the page view model is pointing to the `MdcLookup` component instead of the page view model.
So I cannot make use of any of the attributes or properties of the page view model.

https://gist.dumber.app/?gist=01ac584061194a3093bb58cec8bbe8a6

**Comment by MaximBalaganskiy** [comment]
In this case options function should be an arrow function or bound to a particular this
```ts
getOptions = (filter: string, value: unknown) => { 
  // do something
}
```

**Comment by arjendeblok** [comment]
Nice. Creating an arrow function in the page view model works (never done that before).
