### ISSUE TITLE
mdc-data-table Pagination Demo

### ISSUE THREAD

**Issue by matthewcorven** [aurelia-ui-toolkits/aurelia-mdc-web#19]
[Pagination demo](https://aurelia-ui-toolkits.github.io/aurelia-mdc-web/#/data-table/examples) shows only 3 items despite apparent 35 items in array.  Also does not update items when controls for page size or forward/back.
![2020-10-25_1-11-40](https://user-images.githubusercontent.com/27839633/97099427-344b8200-165f-11eb-9c9c-1f7bc70eea68.gif)

**Comment by MaximBalaganskiy** [comment]
The demo does not fetch any data. The real app should listen to navigation events and load data accordingly.
