### ISSUE TITLE
Assumes pre-existing installation of aurelia-typed-observable-plugin

### ISSUE THREAD

**Issue by sousekd** [aurelia-ui-toolkits/aurelia-mdc-web#20]
Following the Getting Started guide with Aurelia MDC v1.1.4 on an empty Aurela v1.3.1 project (CLI bundler) with `aurelia.use.plugin(PLATFORM.moduleName('@aurelia-mdc-web/all'))` causes `au build` to fail due to missing **package.json** of **aurelia-typed-observable-plugin**. Manually installing the dependency with `npm i aurelia-typed-observable-plugin` before the build resolves the issue.

**Comment by MaximBalaganskiy** [comment]
Thanks, I'll promote it to hard dependencies
