### ISSUE TITLE
Circular Progress Documentation

### ISSUE THREAD

**Issue by jockjocko** [aurelia-ui-toolkits/aurelia-mdc-web#21]
I'm only including individual components

The documentation for [Circular Progress](https://aurelia-ui-toolkits.github.io/aurelia-mdc-web/#/circular-progress/api), says to include:

`
@use '@material/circular-progress/mdc-circular-progress';
@use '@material/circular-progress';
@use "@aurelia-mdc-web/circular-progress";
`

However this results in the error.
`SassError: There's already a module with namespace "circular-progress".`

Do I need to include both packages `@use '@material/circular-progress';
@use "@aurelia-mdc-web/circular-progress";` for the component to work correctly?

Version used:
`
  "sass": "^1.26.11",
 "sass-loader": "^10.0.2",
 "@aurelia-mdc-web/circular-progress": "^1.1.4",
`

**Comment by MaximBalaganskiy** [comment]
Yes, both are needed. Set an alias for one of them.

**Comment by MaximBalaganskiy** [comment]
Actually, `@use '@material/circular-progress';` can be removed

**Comment by jockjocko** [comment]
> Actually, `@use '@material/circular-progress';` can be removed


Great thanks 👍
