### ISSUE TITLE
mdc-text-field prefix and suffix prevents click to focus

### ISSUE THREAD

**Issue by swalters** [aurelia-ui-toolkits/aurelia-mdc-web#22]
I'm using a large prefix text.  If I try to click into the input box where the prefix text would be, the input does not get focus.

Can be recreated in docs by trying to click on the left.
![image](https://user-images.githubusercontent.com/195646/98269489-67412000-1f53-11eb-9e7f-df2870893ae4.png)

**Comment by MaximBalaganskiy** [comment]
The only way to make it work would be to use `<label mdc-text-field>` syntax.
Due to possible performance issues I would not want to pre-process all templates to automatically replace `<mdc-text-field>` with that.

**Comment by MaximBalaganskiy** [comment]
As a second thought, I've tried auto replacement. It does not seem to slow down the demo app with a bunch of text fields. We'll see how it goes and act on results.
