### ISSUE TITLE
mdc-text-field label disappears on focus with options: fullwidth, outlined

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-mdc-web#24]
**Version**
`@aurelia-mdc-web/text-field`: 1.1.6

**View**
```html
<mdc-layout-grid-cell span="12">
    <mdc-text-field
        label="Search"
        outlined
        fullwidth
        value.bind="_searchQuery"
        keydown.delegate="_filter() & debounce"
    >
        <mdc-icon mdc-text-field-icon leading>search</mdc-icon>
    </mdc-text-field>
</mdc-layout-grid-cell>
```
**Screenshot**
![image](https://user-images.githubusercontent.com/572453/98386575-a7d29380-2050-11eb-8d65-1995849636ef.png)

**Comment by MaximBalaganskiy** [comment]
Could you please create a gist with the issue? The link to the gist template is on the front page of the package.

**Comment by MaximBalaganskiy** [comment]
I think in MDCv7 fullwidth hid the label. Anyway, looks like in MDC v8 fullwidth has been removed

**Comment by mreiche** [comment]
Bug not present in `2.0.0` (`MDC v8`)
