### ISSUE TITLE
mdc-select change.delegate triggered twice

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-mdc-web#25]
**Version**
`@aurelia-mdc-web/select`: 1.1.6
**View**
```html
<mdc-select label="Status"
            value.bind="_selectedStatus"
            change.delegate="_filter()"
            outlined="true"
>
    <mdc-list>
        <mdc-list-item>(All)</mdc-list-item>
        <mdc-list-item repeat.for="status of _availableStatuses"
                       value.bind="status"
        >
            <span>${status|statusName}</span>
        </mdc-list-item>
    </mdc-list>
</mdc-select>
```

**ViewModel**
```typescript
private _filter() {
    const queryParams:any = {};

    if (this._selectedStatus) {
        queryParams.status = this._selectedStatus;
    }
    queryParams.configurationMethods = this._configurationMethods;

    console.log("filter", queryParams);
    this.updateUrl(queryParams);
}
```
**Screenshot**
![image](https://user-images.githubusercontent.com/572453/98388380-f97c1d80-2052-11eb-84bc-45e7204ee397.png)

**Browser-Log**
![image](https://user-images.githubusercontent.com/572453/98388469-1c0e3680-2053-11eb-9bf9-78dd46f61455.png)

**Comment by MaximBalaganskiy** [comment]
Version 1.1.6 does not need explicit mdc-list element. Please remove that or upgrade to v2 of the bridge.

**Comment by mreiche** [comment]
Ah ok. How do I get to the "old" docu?

**Comment by MaximBalaganskiy** [comment]
Fetch mdc7 branch and start the demo app.

**Comment by mreiche** [comment]
Event was triggered twice because of `mdc-list` element not necessary in version < 2
