### ISSUE TITLE
mdc-select item not initialized from bound value

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-mdc-web#26]
**Version**
`@aurelia-mdc-web/select`: 1.1.6

**View**
```html
<mdc-select label="Status"
            value.bind="_selectedStatus"
            outlined="true"
>
    <mdc-list>
        <mdc-list-item repeat.for="status of _availableStatuses" value.bind="status">
            <span>${status}</span>
        </mdc-list-item>
    </mdc-list>
</mdc-select>
```
**ViewModel**
```typescript
activate(
    params: any,
    routeConfig: RouteConfig,
    navInstruction: NavigationInstruction
) {
    this._selectedStatus = "passed";
}
```
**Actual Screenshot**
![image](https://user-images.githubusercontent.com/572453/98389921-fe41d100-2054-11eb-865c-bbe465e6c922.png)

**Expected**
![image](https://user-images.githubusercontent.com/572453/98389957-0bf75680-2055-11eb-9897-2f1571065f5e.png)

**Comment by MaximBalaganskiy** [comment]
Version 1.1.6 does not need explicit mdc-list element. Please remove that or upgrade to v2 of the bridge.

**Comment by MaximBalaganskiy** [comment]
I cannot reproduce the issue in the gist
https://gist.dumber.app/?gist=4fb62077f5564275f96253b8e708314a

**Comment by mreiche** [comment]
It works when `_availableStatuses` is already initialized. But not when its lazy loaded like...
```typescript
const loadAsync = new Promise((resolve, reject) => {
    window.setTimeout(() => {
        resolve( ["Katze", "passed", "Maus"]);
        }, 2000)
});

loadAsync.then((value:string[]) => {
    this._availableStatuses = value;
});
```

Unfortunately, I cannot edit your Gist because of rate limit hit.

**Comment by MaximBalaganskiy** [comment]
You can only set the value after the select is populated with options, otherwise it cannot find the corresponding list item.

**Comment by MaximBalaganskiy** [comment]
I've updated the gist for async load, no issue

**Comment by mreiche** [comment]
But shouldn't it work like that? https://gist.dumber.app/?gist=8204b93b878e0f8ad4f027ace68d06d9

**Comment by MaximBalaganskiy** [comment]
This cannot work. After activate the widget's value is set but there are no items to match that value with.

**Comment by mreiche** [comment]
But this is the way I used to implement that the Aurelia way using regular `select` elements.

I've updated https://gist.dumber.app/?gist=8204b93b878e0f8ad4f027ace68d06d9 by
```html
<select value.bind="_selectedStatus">
     <option repeat.for="status of _availableStatuses" value.bind="status">${status}</option>
</select>
```

**Comment by MaximBalaganskiy** [comment]
Aurelia treats native select in a special way, unlike non-native MDC widget. I'll see if I can do anything about it

**Comment by MaximBalaganskiy** [comment]
Hopefully this will be sufficient. I've modified the binding observer to monitor `mdc-list-item` mutations.
It will wait for options before trying to pass the current value to the element.
But once options has been set at least once any subsequent options changes will pull the value **from** the element, possibly overwriting the current value if it is not present in the current list.

**Comment by mreiche** [comment]
> But once options has been set at least once any subsequent options changes will pull the value **from** the element, possibly overwriting the current value if it is not present in the current list.

Doesn't sound wrong to me.

Thanks. I really apprecriate your passion.
