### ISSUE TITLE
mdc-list keeps interactive with nonInteractive option

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-mdc-web#27]
**Version**
2.0.0

**View**
```html
<mdc-list nonInteractive="true">
    <mdc-list-item>Hallo</mdc-list-item>
    <mdc-list-item>Liebe</mdc-list-item>
    <mdc-list-item>Welt</mdc-list-item>
</mdc-list>
```

**Actual**
![image](https://user-images.githubusercontent.com/572453/98818867-6cf3a580-242c-11eb-95e6-3674c65331a4.png)
* Hover and Ripple are enabled

**Expected**
* Hover and Ripple are disabled

**Gist**
https://gist.dumber.app/?gist=d4c7e911d2a42aca9a9f3e35ceba3587

**Comment by MaximBalaganskiy** [comment]
Please use kebab style attributes

**Comment by MaximBalaganskiy** [comment]
Plus ="true" is not necessary for bool attributes

**Comment by mreiche** [comment]
I see no change with
```html
<mdc-list non-interactive>
```
(https://gist.dumber.app/?gist=d4c7e911d2a42aca9a9f3e35ceba3587)

What I'm doing wrong?
How can I contribute to the demo and documentation?

**Comment by MaximBalaganskiy** [comment]
Apparently, it was removed in mdc8. Need to clean up.
Contributing is easy. See https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/blob/master/docs/developer.md
The demo app is the docs essentially. 
`npm run doc` builds the api reference.

**Comment by MaximBalaganskiy** [comment]
btw, remember to clean the local bundler cache in dumber gist, otherwise you might still use the previous version

**Comment by MaximBalaganskiy** [comment]
![image](https://user-images.githubusercontent.com/3712700/98916225-0307f880-251f-11eb-86f6-41cdc9d151fd.png)

**Comment by mreiche** [comment]
This is the workarround
```html
<ul class="mdc-list">
    <li class="mdc-list-item" style="cursor:initial">Katze</li>
    <li class="mdc-list-item">Affe</li>
    <li class="mdc-list-item">Kuh</li>
</ul>
```
