### ISSUE TITLE
Documentation has incorrect install scripts

### ISSUE THREAD

**Issue by CollinHerber** [aurelia-ui-toolkits/aurelia-mdc-web#28]
https://aurelia-ui-toolkits.github.io/aurelia-mdc-web/#/getting-started

Just wanted to point out that you're yarn and npm scripts:
npm i @aurelia-mdc/all

They are incorrect. Should be 
@aurelia-mdc-web/all

**Comment by CollinHerber** [comment]
I looked for a repo for the documentation but didn't find anything.

Perhaps create a repo for this so people can contribute to the documentation?

Love what I see, looking forward to trying this out. I was making my own version of exactly this when stumbling across this.

**Comment by MaximBalaganskiy** [comment]
The demo app is deployed to github pages and serves the documentation purpose. You can PR directly to this repo.

**Comment by CollinHerber** [comment]
Got it. Thanks.
