### ISSUE TITLE
[Bug] [Documentation] Select API Button doesn't work

### ISSUE THREAD

**Issue by CollinHerber** [aurelia-ui-toolkits/aurelia-mdc-web#29]
https://aurelia-ui-toolkits.github.io/aurelia-mdc-web/#/select

Notice that clicking the "API" tab does not switch to the API view.

Console spits out: `TypeError: Cannot read property 'children' of undefined`

**Comment by MaximBalaganskiy** [comment]
Yeah, API sections "after" lookup are not complete yet

**Comment by CollinHerber** [comment]
Gotcha. Well I'm glad to contribute to this repository as I said I was literally creating exactly this so my time can be spent here instead. Are we interested in having additional components that don't come stock with MD? 

For example I made this file input with state styling while making my own version.
https://t.gyazo.com/teams/chicksgold/2638715bbc554a28663839801ec6266b.png

I'd be happy to contribute this code if wanted. Just would need a touchup to be in this project format.

**Comment by MaximBalaganskiy** [comment]
Absolutely, all contributions are welcome. Ping me on Discord if you need any interactive help

**Comment by CollinHerber** [comment]
Is there a Discord server listed somewhere? I'm not finding anything in/out of the repo.

**Comment by MaximBalaganskiy** [comment]
I hang around in Aurelia chats (#components or #troubleshooting are probably the best places), you can PM as well

**Comment by MaximBalaganskiy** [comment]
Fixed via 8ebd954e8383fbc56a339f1c99d087cc58dd9ded
