### ISSUE TITLE
[question] How to make mdc-lookup data async?

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-mdc-web#32]
As seen in: https://gist.dumber.app/?gist=81d9964a3ca5f034556281f25fd6ef2a loading the lookup data ansynchronous will results into error messages.

![image](https://user-images.githubusercontent.com/572453/101894207-1e116b00-3ba6-11eb-851d-57b1b87c228f.png)

Is there a way to refresh programmatically or should the component handle `optionsChanged()`?

**Comment by MaximBalaganskiy** [comment]
The gist has got selects only

**Comment by MaximBalaganskiy** [comment]
I suspect that your `getOptions` function tries to access an array which has not been loaded yet. In this case you can just chain promises and return the combined one from the function.

**Comment by mreiche** [comment]
Sorry, I forgot to save the gist. I refactored to use a load function and it works now.
