### ISSUE TITLE
[question] How to make rich tooltips?

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-mdc-web#39]
Original mdc-tooltip supports using rich HTML in tooltip containers (https://github.com/material-components/material-components-web/blob/master/packages/mdc-tooltip/README.md) but this bridge doesn't seem to support this or it's not documented.

**Comment by MaximBalaganskiy** [comment]
Rich tooltips weren't fully implemented because docs weren't complete at the time. You can probably use `mdc-tooltip` element (not attribute) the way docs suggest, if it does not work then a proper implementation will be needed.
```
<div class="mdc-tooltip-wrapper--rich">
  <button mdc-button aria-describedby="tt0" ref="button">Button</button>
  <mdc-tooltip rich anchor-elem.bind="button">
    <p class="mdc-tooltip__content">
         Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
         pretium vitae est et dapibus. Aenean sit amet felis eu lorem fermentum
         aliquam sit amet sit amet eros.
    </p>
  </mdc-tooltip>
</div>
```

**Comment by mreiche** [comment]
This works, but unfortunately not inside a mdc-list.
