### ISSUE TITLE
[BUG] Unable to Toggle Autocomplete on mdc-text-input

### ISSUE THREAD

**Issue by CollinHerber** [aurelia-ui-toolkits/aurelia-mdc-web#40]
Based on the code here: https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/blob/master/packages/text-field/src/mdc-text-field.ts#L162 it should not autocomplete if you supply nothing however it does appear that autocomplete is still functioning.

There is also no examples of this in the documentation and may be worth adding something to the demo site.

Also instead of just checking undefined, maybe also checking false and off. I highly suggesting checking for `off` as that is native HTML verbage.

**Comment by MaximBalaganskiy** [comment]
If you don't supply autocomplete then it does not set the attribute on the native input which then equals default "".
If you supply "off" that is what the native input will get. Could you please elaborate on checking for it?

**Comment by CollinHerber** [comment]
> If you don't supply autocomplete then it does not set the attribute on the native input which then equals default "".
> If you supply "off" that is what the native input will get. Could you please elaborate on checking for it?

Ahh, looking at that again I see now. I didn't realize that `this.input_` was a HTMLInputElement. 
Then I'm not really sure why when I supplied "off" it wasn't working. I tried "off" then went to other things like "false" but had no luck with anything.

**Comment by MaximBalaganskiy** [comment]
By not working you mean browser or a password manager still fills it in? Does it work with a native input on the same page?

**Comment by MaximBalaganskiy** [comment]
Please reopen if still relevant
