### ISSUE TITLE
[tooltip] How to use with a dynamic property (binding)?

### ISSUE THREAD

**Issue by green3g** [aurelia-ui-toolkits/aurelia-mdc-web#41]
I've tried passing a tooltip value on an element from a property in a variety of ways. Each case leaves the tooltip "undefined". 

![image](https://user-images.githubusercontent.com/5471079/109056700-610fb480-76a6-11eb-9b63-20ed04506458.png)

```html
<button mdc-tooltip="${myProp}"></button>

<button mdc-tooltip.bind="myProp"></button>

<button mdc-tooltip="value: ${myProp};"></button>

<button mdc-tooltip="${'value: ' + myProp}"></button> 

```

Anything else I can try, or know where a good place for a fix would be? Happy to look into it but I'm not seeing anything obvious in the tooltip package where value is getting used.

**Comment by MaximBalaganskiy** [comment]
Please try `mdc-tooltip="value.bind: myProp"`

**Comment by green3g** [comment]
Nice! That worked. 

![image](https://user-images.githubusercontent.com/5471079/109186429-85c36500-7756-11eb-86ab-8379b4a813bb.png)

**Comment by MaximBalaganskiy** [comment]
Just a side note, usually Google displays triple dots button for multiple row actions

**Comment by green3g** [comment]
@MaximBalaganskiy  - I'm running into a similar issue with binding mdc-linear-progress to a decimal value. I can't seem to get the progress value to update. 

For example:

```html
<!-- percentComplete = 0.5 -->
<mdc-linear-progress if.bind="pending" progress="value.bind: percentComplete"></mdc-linear-progress>
<mdc-linear-progress if.bind="pending" progress="${percentComplete}></mdc-linear-progress>
<mdc-linear-progress if.bind="pending" progress.bind="percentComplete"></mdc-linear-progress>
```

Any suggestions on this one ? 

** Edit: **

Nevermind! I had a bug in my app that wasn't working. 

progres.bind="percentComplete" works fine
