### ISSUE TITLE
[bug] Crashes app when trying to import only slider

### ISSUE THREAD

**Issue by pkkummermo** [aurelia-ui-toolkits/aurelia-mdc-web#43]
When trying to import only the slider-component, ie `@aurelia-mdc-web/slider`, it crashes the page where I use it with

HTML:
```html
<mdc-slider min="0" max="120" value.bind="someData" name="test"></mdc-slider>
```

Console:
```
ERROR [app-router] Error: No Aurelia APIs are defined for the element: "DIV".
```

The debug shows that the plugins is configured properly
```
DEBUG [aurelia] Configured plugin @aurelia-mdc-web/slider.
```

If i install the `@aurelia-mdc-web/all`-package however, the error goes away and everything works. Is there an additional package I need that's not documented?

**Comment by MaximBalaganskiy** [comment]
Please `aurelia.use.plugin(PLATFORM.moduleName('@aurelia-mdc-web/ripple'))` until the next release

**Comment by pkkummermo** [comment]
Willdo! And thank you for the quick reply <3
