### ISSUE TITLE
Linear Progress: open attribute set initially to false does not work

### ISSUE THREAD

**Issue by arjendeblok** [aurelia-ui-toolkits/aurelia-mdc-web#44]
I am using the linear progress a lot. When it's `open` attribute is initially `true` and then becomes `false` then the linear progress disappears.
When I set `open` initially to `false` then it is visible directly. So I cannot start with an invisible progress and let make visible at a later moment.
My use case is that when a user submits a form that the linear progress is shown while submitting the form. So it is not shown when the user is filling the form.

**Comment by MaximBalaganskiy** [comment]
released
