### ISSUE TITLE
Providing skeleton application

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-mdc-web#49]
Hi. I've created a minimal skeleton application with the main features:

- Aurelia-MDC integration
  - Basic Drawer
  - One main router with one sub route
- SCSS integration
- Injection of dev/prod configuration
- Support for static assets (images, fonts)
- Webpack integration
- Bundle size analyzer

I made it to quickly create new applications with basic needs: https://github.com/mreiche/aurelia-material-skeleton
I just want to know if you need that and if it's worth to link it here in the documentation?

**Comment by MaximBalaganskiy** [comment]
Sure, thanks for the suggestion. Will a reference in quick links work?

**Comment by mreiche** [comment]
For me yes. I try to keep the skeleton up-to-date to latest aurelia-mdc release.

**Comment by MaximBalaganskiy** [comment]
Does it make sense to make it work with "npx makes"?

**Comment by arjendeblok** [comment]
I thought about `npx makes `too when I looked at the skeleton.
Thumbs up for this.

**Comment by MaximBalaganskiy** [comment]
Could be `npx makes aurelia-material-skeleton`. For this we would need to create an `aurelia-material-skeleton` org and push the `new` repo to it.

**Comment by mreiche** [comment]
Can someone provide a quickstart link or hints for `npx makes`?

**Comment by MaximBalaganskiy** [comment]
https://makes.js.org/get-started

**Comment by mreiche** [comment]
Ok, let me take a look onto https://makes.js.org/get-started#define-a-skeleton. I come back to you soon.

**Comment by MaximBalaganskiy** [comment]
Any luck with this one? As far as I understood, in the simplest scenario, just creating a `new` folder under an org is enough.

**Comment by MaximBalaganskiy** [comment]
I've added https://github.com/aurelia-mdc-web/new.
@mreiche You are invited to the new org. Feel free to update the skeleton
