### ISSUE TITLE
Error in MDCDataTable in @aurelia-mdc-web/all@6.2.6-au2

### ISSUE THREAD

**Issue by stuartbale** [aurelia-ui-toolkits/aurelia-mdc-web#51]
Uncaught TypeError: Cannot read property 'checked' of undefined
    at Object.isCheckboxAtRowIndexChecked (mdc-data-table.js?2efa:245)
    at MDCDataTableFoundation.handleRowCheckboxChange (foundation.js?9ba6:183)
    at MdcDataTable.handleRowCheckboxChange (mdc-data-table.js?2efa:104)
    at MdcDataTable.handleEvent (mdc-data-table.js?2efa:160)
<img width="674" alt="Screen Shot 2021-07-30 at 4 26 55 PM" src="https://user-images.githubusercontent.com/1775472/127600247-29fa880c-fd29-40c2-a045-581de77f82c8.png">

**Comment by MaximBalaganskiy** [comment]
Could you please add some background info on what caused this?

**Comment by MaximBalaganskiy** [comment]
Are there any input elements in the table other than `mdc-checkbox`?

**Comment by stuartbale** [comment]
Hey Max - this is the HTML for the table. It has a row at the top to allow users to add a new item.
```
    <mdc-data-table busy.bind="busy">
        <table>
            <thead>
                <tr class="mdc-data-table__header-row">
                .... // table header cells removed
                </tr>
            </thead>
            <tbody>
                <tr mdc-data-table-row>
                    <td>
                        <mdc-text-field outlined label="Code" value.bind="newCode"></mdc-text-field>
                    </td>
                    <td colspan="5">
                        <mdc-button outlined click.trigger="addShare()">Add Share</mdc-button>
                    </td>
                </tr>
                <tr mdc-data-table-row repeat.for="share of shares" click.trigger="showShare(share.code)">
                .... // table cells removed
                </tr>
            </tbody>
        </table>
    </mdc-data-table>
```
The error occurs when I enter a value in the textfield and then tab out.

does that help?

**Comment by MaximBalaganskiy** [comment]
Yes, just as I thought - an input in the table fires a change event. This is fixable.

**Comment by stuartbale** [comment]
ok cool - thanks for the insanely quick response!

**Comment by stuartbale** [comment]
@MaximBalaganskiy - if I npm install mdc@v12, will aurelia-mdc use that? Or do I need to wait until you've updated it?

**Comment by MaximBalaganskiy** [comment]
You'll need to wait till the dependency is upgraded
