### ISSUE TITLE
[question] How to use Snackbars?

### ISSUE THREAD

**Issue by case112** [aurelia-ui-toolkits/aurelia-mdc-web#53]
I have found this library super helpful to implement MDC in my Aurelia application, thanks for all the work! 👏

I'm relatively new to working with Aurelia and MDC but I've been able to follow most of the examples and use them on my Aurelia app. One thing I could not figure out from the examples is how to properly use Snackbars.

I can see that in the example section you call a method with click.delegate - for example:
`<button mdc-button raised click.delegate="dismissIcon()">Dismiss Icon</button>`

How exactly should I implement this method in my view-model to produce a Snackbar?

**Comment by mreiche** [comment]
@MaximBalaganskiy The Typescript code example is missing here: https://aurelia-ui-toolkits.github.io/aurelia-mdc-web/#/snackbar/examples
Unfortunately, I couldn't find the showcase repository to point that out.

**Comment by MaximBalaganskiy** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/blob/master/packages/app/src/views/snackbar/examples.ts

**Comment by case112** [comment]
Thanks for your help!
