### ISSUE TITLE
A question on theme support

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-mdc-web#54]
I tried to implement a "dark theme" by setting up the primary, secondary and background color like described here: https://material.io/develop/web/theming/color

But the `$background` variable is ignored in aurelia-mdc and the application keeps still "light".

```sass
@use "@material/theme" with (
    $primary: #f00,
    $on-primary: #ff0,
    $secondary: #f0f,
    $on-secondary: #0ff,
    $background: #333,
    $surface: #aaa,
    $on-surface: #0f0,
);
```

**Comment by MaximBalaganskiy** [comment]
The bridge does not do anything with styles. I've applied the theme above to the demo app and the background does get set to the variables 
![image](https://user-images.githubusercontent.com/3712700/130373638-10073261-0797-4b97-a845-3e769f2bb397.png)

I had a brief look at the MDC sass files and the background is not used anywhere, I think you are supposed to set it manually on the controls you need
```
    background-color: var(--mdc-theme-background);
```

**Comment by mreiche** [comment]
It looks like the whole mdc theming is broken.

1. It doesn't follow the documentation. Defining `$text-primary-on-light` fails, but described at "Material theme keys with theme.property()"

2. in `_theme-color.scss` is defined
```scss
$on-surface: if(contrast-tone($surface) == 'dark', #000, #fff) !default;
```
which would result on a black color on a dark surface, which doesn't make any sense.

3. Using variables doesn't work for me
```scss
.body {
    background-color: var(--mdc-theme-background);
}
```

I'm currently unable to support a dark theme without deeper unterstanding of the material theme or manually overriding a lot of styles.

**Comment by MaximBalaganskiy** [comment]
Perhaps, MDC repository would be a better place for this question as I doubt many eyes will see it here.

**Comment by mreiche** [comment]
Yes you are right. I just want to know if anyone was able to create a dark theme.

I created a bug ticket here: https://github.com/material-components/material-components-web/issues/7340 and it looks like that many people having issues with that.
