### ISSUE TITLE
Font size of list items of drawer not correct

### ISSUE THREAD

**Issue by arjendeblok** [aurelia-ui-toolkits/aurelia-mdc-web#55]
I upgraded from 5.1 to 7.1 and noticed that the font size of the list items in de drawer was increased from 14px to 16px.

They should be 14px (0.875rem). In the past this was done via de selector `.mdc-drawer .mdc-list-item` .
But because of the `mdc-list` changes it does not seem to work anymore.

**Comment by MaximBalaganskiy** [comment]
I guess I'll have to add `mdc-deprecated-list` element. If you don't care about keyboard navigations you probably could just use deprecated classed as a workaround
