### ISSUE TITLE
mdc-switch style missing

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-mdc-web#56]
I'm migrating form `3.x` to `7.1.2` and get the following error message when compiling:

```
 SassError: Can't find stylesheet to import.
       ╷
    60 │ @use '@material/switch/mdc-switch';
       │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       ╵
      src\styles\mdc.scss 60:1  @import
      src\app.scss 22:9         root stylesheet
```
When I remove this line, the switch component keep unstyled.
```scss
//@use '@material/switch/mdc-switch';
@use '@material/switch';
```
![image](https://user-images.githubusercontent.com/572453/131629103-3d72e11f-2ed9-4904-b284-a40e96fdd85f.png)

**Comment by MaximBalaganskiy** [comment]
Should be `@use '@material/switch/styles';`

**Comment by mreiche** [comment]
Fixed by using
```scss
@use '@material/switch/styles' as switch-styles;
```
