### ISSUE TITLE
[bug] - list item trailing links are not clickable

### ISSUE THREAD

**Issue by green3g** [aurelia-ui-toolkits/aurelia-mdc-web#58]
I'm not 100% sure if this is a bug but we've discovered that if you include a link in the trailing icon of the list-item the link is not clickable and doesn't work:

```html
      <mdc-list-item repeat.for="file of files" two-line disable-ripple.bind="disableRipple">
        <mdc-icon mdc-list-item-leading>${file.icon}</mdc-icon>
        <mdc-list-item-primary-text>${file.name}</mdc-list-item-primary-text>
        <mdc-list-item-secondary-text>${file.addDate}</mdc-list-item-secondary-text>
        <a href="#/list/examples" mdc-list-item-trailing="icon" aria-label="View more" title="More info">
          <mdc-icon>info</mdc-icon>
        </a>
      </mdc-list-item>
```

In the past it was possible to embed a small link or icon in the list-item-meta markup - (now trailing) but not it seems the list-item takes over the child elements as well. 

Let me know if there's a better way to achieve this.

Version:
        "@aurelia-mdc-web/all": "^7.1.2",

**Comment by MaximBalaganskiy** [comment]
See https://github.com/material-components/material-components-web/issues/7296#issuecomment-894761845

**Comment by green3g** [comment]
Yep - that fixed it. Thank you!
