### ISSUE TITLE
Development guide

### ISSUE THREAD

**Issue by mattpottstj** [aurelia-ui-toolkits/aurelia-mdc-web#59]
Hi, 

Is the development guide up to date as i'd like to contribute with a couple of bug fixes and features but i can't build a forked repo?

After cloning locally, my packages.json file doesn't contain any scripts section so when trying to follow step 5 - From the root of the project, run `npm run refresh` to bootstrap lerna, i just get the general npm error: missing script: refresh.

 Cheers,
Matt

**Comment by MaximBalaganskiy** [comment]
'Npm i && npm run doc && npm start' starts the demo

'Npm run build' builds the packages. You can also build a specific package from its folder.

Due to a bug in Aurelia webpack plugin, you'll need to delete packages dist folders before starting the demo again after build.

**Comment by mattpottstj** [comment]
Thanks for the tips. I've not been able to successfully build all the packages yet, some individual ones i can but any advice on the below:


> @aurelia-mdc-web/monorepo@7.1.3 build C:\Users\matt\Documents\git\github\aurelia-mdc-web
> lage run build --scope @aurelia-mdc-web/* --no-cache --no-deps

info Lage task runner - let's make it
info @aurelia-mdc-web/base build ▶️ start
info @aurelia-mdc-web/elevation build ▶️ start
info @aurelia-mdc-web/icon build ▶️ start
info @aurelia-mdc-web/image-list build ▶️ start
info @aurelia-mdc-web/layout-grid build ▶️ start
info @aurelia-mdc-web/base build ✔️ done  - 27.90s
info @aurelia-mdc-web/card build ▶️ start
info @aurelia-mdc-web/circular-progress build ▶️ start
info @aurelia-mdc-web/drawer build ▶️ start
info @aurelia-mdc-web/floating-label build ▶️ start
info @aurelia-mdc-web/image-list build ✔️ done  - 28.31s
info @aurelia-mdc-web/line-ripple build ▶️ start
info @aurelia-mdc-web/elevation build ✔️ done  - 28.34s
info @aurelia-mdc-web/linear-progress build ▶️ start
info @aurelia-mdc-web/icon build ✔️ done  - 28.62s
info @aurelia-mdc-web/menu-surface build ▶️ start
info @aurelia-mdc-web/layout-grid build ✔️ done  - 28.84s
info @aurelia-mdc-web/ripple build ▶️ start
info @aurelia-mdc-web/floating-label build ❌ fail
info 🏗 Summary
info
info [Tasks Count] success: 5, skipped: 0, incomplete: 8
info ----------------------------------------------
ERR! [@aurelia-mdc-web/floating-label build] ERROR DETECTED
ERR! started
ERR! Running C:\Program Files\nodejs\npm.CMD run build
ERR! > @aurelia-mdc-web/floating-label@7.1.3 prebuild C:\Users\matt\Documents\git\github\aurelia-mdc-web\packages\floating-label
ERR! > rimraf dist
ERR! > @aurelia-mdc-web/floating-label@7.1.3 build C:\Users\matt\Documents\git\github\aurelia-mdc-web\packages\floating-label
ERR! > concurrently "npm:build-ts:*" && concurrently "npm:build-assets:*"
ERR! [build-ts:amd] > @aurelia-mdc-web/floating-label@7.1.3 build-ts:amd C:\Users\matt\Documents\git\github\aurelia-mdc-web\packages\floating-label
ERR! [build-ts:amd] > tsc -p tsconfig.build.json -t es5 -m amd      --outDir dist/amd
ERR! [build-ts:amd]
ERR! [build-ts:types] > @aurelia-mdc-web/floating-label@7.1.3 build-ts:types C:\Users\matt\Documents\git\github\aurelia-mdc-web\packages\floating-label
ERR! [build-ts:types] > tsc -p tsconfig.build.json --skipLibCheck -d --emitDeclarationOnly --declarationDir dist/types
ERR! [build-ts:types]
ERR! [build-ts:es6] > @aurelia-mdc-web/floating-label@7.1.3 build-ts:es6 C:\Users\matt\Documents\git\github\aurelia-mdc-web\packages\floating-label
ERR! [build-ts:es6] > tsc -p tsconfig.build.json -t es6 -m es6      --outDir dist/es2015
ERR! [build-ts:es6]
ERR! [build-ts:ntv] > @aurelia-mdc-web/floating-label@7.1.3 build-ts:ntv C:\Users\matt\Documents\git\github\aurelia-mdc-web\packages\floating-label
ERR! [build-ts:ntv] > tsc -p tsconfig.build.json -t es5 -m es6      --outDir dist/native-modules
ERR! [build-ts:ntv]
ERR! [build-ts:cjs] > @aurelia-mdc-web/floating-label@7.1.3 build-ts:cjs C:\Users\matt\Documents\git\github\aurelia-mdc-web\packages\floating-label
ERR! [build-ts:cjs] > tsc -p tsconfig.build.json -t es5 -m commonjs --outDir dist/commonjs
ERR! [build-ts:cjs]
ERR! src/mdc-floating-label.ts(3,30): error TS2307: Cannot find module '@aurelia-mdc-web/base' or its corresponding type declarations.
ERR! src/mdc-floating-label.ts(11,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(19,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:amd] src/mdc-floating-label.ts(27,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(31,17): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:amd] src/mdc-floating-label.ts(36,37): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:amd] src/mdc-floating-label.ts(37,40): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:amd] src/mdc-floating-label.ts(38,48): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(39,62): error TS2339: Property 'listen' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:amd] src/mdc-floating-label.ts(40,64): error TS2339: Property 'unlisten' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(3,30): error TS2307: Cannot find module '@aurelia-mdc-web/base' or its corresponding type declarations.
ERR! src/mdc-floating-label.ts(11,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(19,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:es6] src/mdc-floating-label.ts(27,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:es6] src/mdc-floating-label.ts(31,17): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(36,37): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:es6] src/mdc-floating-label.ts(37,40): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:es6] src/mdc-floating-label.ts(38,48): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:es6] src/mdc-floating-label.ts(39,62): error TS2339: Property 'listen' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:es6] src/mdc-floating-label.ts(40,64): error TS2339: Property 'unlisten' does not exist on type 'MdcFloatingLabel'.
ERR!  ERR! code ELIFECYCLE
ERR! [build-ts:amd] npm ERR! errno 2
ERR!  @aurelia-mdc-web/floating-label@7.1.3 build-ts:amd: `tsc -p tsconfig.build.json -t es5 -m amd      --outDir dist/amd`
ERR! [build-ts:amd] npm ERR! Exit status 2
ERR! [build-ts:amd] npm ERR!
ERR!  Failed at the @aurelia-mdc-web/floating-label@7.1.3 build-ts:amd script.
ERR! [build-ts:amd] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
ERR!  WARN Local package.json exists, but node_modules missing, did you mean to install?
ERR! [build-ts:amd] npm ERR! A complete log of this run can be found in:
ERR! [build-ts:amd] npm ERR!     C:\Users\matt\AppData\Roaming\npm-cache\_logs\2021-09-11T08_15_32_570Z-debug.log
ERR! src/mdc-floating-label.ts(3,30): error TS2307: Cannot find module '@aurelia-mdc-web/base' or its corresponding type declarations.
ERR! npm run build-ts:amd exited with code 2
ERR! src/mdc-floating-label.ts(11,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(19,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(27,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(31,17): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:ntv] src/mdc-floating-label.ts(36,37): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:ntv] src/mdc-floating-label.ts(37,40): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:ntv] src/mdc-floating-label.ts(38,48): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(39,62): error TS2339: Property 'listen' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:ntv] src/mdc-floating-label.ts(40,64): error TS2339: Property 'unlisten' does not exist on type 'MdcFloatingLabel'.
ERR!  ERR! code ELIFECYCLE
ERR! [build-ts:es6] npm ERR! errno 2
ERR!  @aurelia-mdc-web/floating-label@7.1.3 build-ts:es6: `tsc -p tsconfig.build.json -t es6 -m es6      --outDir dist/es2015`
ERR! [build-ts:es6] npm ERR! Exit status 2
ERR! [build-ts:es6] npm ERR!
ERR! [build-ts:es6] npm ERR! Failed at the @aurelia-mdc-web/floating-label@7.1.3 build-ts:es6 script.
ERR! [build-ts:es6] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
ERR!  WARN Local package.json exists, but node_modules missing, did you mean to install?
ERR! npm ERR! A complete log of this run can be found in:
ERR! [build-ts:es6] npm ERR!     C:\Users\matt\AppData\Roaming\npm-cache\_logs\2021-09-11T08_15_34_390Z-debug.log
ERR! npm run build-ts:es6 exited with code 2
ERR!  ERR! code ELIFECYCLE
ERR! [build-ts:ntv] npm ERR! errno 2
ERR! ERR! @aurelia-mdc-web/floating-label@7.1.3 build-ts:ntv: `tsc -p tsconfig.build.json -t es5 -m es6      --outDir dist/native-modules`
ERR! [build-ts:ntv] npm ERR! Exit status 2
ERR! [build-ts:ntv] npm ERR!
ERR! [build-ts:ntv] npm ERR! Failed at the @aurelia-mdc-web/floating-label@7.1.3 build-ts:ntv script.
ERR! [build-ts:ntv] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
ERR!  WARN Local package.json exists, but node_modules missing, did you mean to install?
ERR! npm ERR! A complete log of this run can be found in:
ERR! [build-ts:ntv] npm ERR!     C:\Users\matt\AppData\Roaming\npm-cache\_logs\2021-09-11T08_15_38_592Z-debug.log
ERR! src/mdc-floating-label.ts(3,30): error TS2307: Cannot find module '@aurelia-mdc-web/base' or its corresponding type declarations.
ERR! src/mdc-floating-label.ts(11,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(19,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:types] src/mdc-floating-label.ts(27,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:types] src/mdc-floating-label.ts(31,17): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(36,37): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:types] src/mdc-floating-label.ts(37,40): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:types] src/mdc-floating-label.ts(38,48): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(39,62): error TS2339: Property 'listen' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:types] src/mdc-floating-label.ts(40,64): error TS2339: Property 'unlisten' does not exist on type 'MdcFloatingLabel'.
ERR! npm run build-ts:ntv exited with code 2
ERR! src/mdc-floating-label.ts(3,30): error TS2307: Cannot find module '@aurelia-mdc-web/base' or its corresponding type declarations.
ERR! src/mdc-floating-label.ts(11,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(19,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(27,10): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! [build-ts:cjs] src/mdc-floating-label.ts(31,17): error TS2339: Property 'foundation' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(36,37): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(37,40): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(38,48): error TS2339: Property 'root' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(39,62): error TS2339: Property 'listen' does not exist on type 'MdcFloatingLabel'.
ERR! src/mdc-floating-label.ts(40,64): error TS2339: Property 'unlisten' does not exist on type 'MdcFloatingLabel'.
ERR!  ERR! code ELIFECYCLE
ERR! [build-ts:types] npm ERR! errno 2
ERR!  @aurelia-mdc-web/floating-label@7.1.3 build-ts:types: `tsc -p tsconfig.build.json --skipLibCheck -d --emitDeclarationOnly --declarationDir dist/types`
ERR!  ERR! Exit status 2
ERR!  ERR!
ERR! ERR! Failed at the @aurelia-mdc-web/floating-label@7.1.3 build-ts:types script.
ERR!  This is probably not a problem with npm. There is likely additional logging output above.
ERR!  WARN Local package.json exists, but node_modules missing, did you mean to install?
ERR! npm ERR! A complete log of this run can be found in:
ERR! [build-ts:types] npm ERR!     C:\Users\matt\AppData\Roaming\npm-cache\_logs\2021-09-11T08_15_41_780Z-debug.log
ERR! npm run build-ts:types exited with code 2
ERR!  ERR! code ELIFECYCLE
ERR! [build-ts:cjs] npm ERR! errno 2
ERR!  @aurelia-mdc-web/floating-label@7.1.3 build-ts:cjs: `tsc -p tsconfig.build.json -t es5 -m commonjs --outDir dist/commonjs`
ERR! [build-ts:cjs] npm ERR! Exit status 2
ERR! [build-ts:cjs] npm ERR!
ERR! [build-ts:cjs] npm ERR! Failed at the @aurelia-mdc-web/floating-label@7.1.3 build-ts:cjs script.
ERR! [build-ts:cjs] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
ERR! [build-ts:cjs] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
ERR!  ERR! A complete log of this run can be found in:
ERR!      C:\Users\matt\AppData\Roaming\npm-cache\_logs\2021-09-11T08_15_43_213Z-debug.log
ERR! [build-ts:cjs] npm run build-ts:cjs exited with code 2
ERR!  ELIFECYCLE
ERR!  1
ERR! ERR! @aurelia-mdc-web/floating-label@7.1.3 build: `concurrently "npm:build-ts:*" && concurrently "npm:build-assets:*"`
ERR! npm ERR! Exit status 1
ERR!  Failed at the @aurelia-mdc-web/floating-label@7.1.3 build script.
ERR!  This is probably not a problem with npm. There is likely additional logging output above.
ERR!  WARN Local package.json exists, but node_modules missing, did you mean to install?
ERR! npm ERR! A complete log of this run can be found in:
ERR!      C:\Users\matt\AppData\Roaming\npm-cache\_logs\2021-09-11T08_15_43_911Z-debug.log
ERR! failed
info ----------------------------------------------
info Took a total of 1m 16.88s to complete
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @aurelia-mdc-web/monorepo@7.1.3 build: `lage run build --scope @aurelia-mdc-web/* --no-cache --no-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @aurelia-mdc-web/monorepo@7.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by MaximBalaganskiy** [comment]
Have you got the v7 of npm? It should have symlinked the packages to node_modules

**Comment by mattpottstj** [comment]
Spot on, was on last v6, upgrading sorted it. 
Will update the developer doc in my first PR. Thanks.
