### ISSUE TITLE
Data table navigation and sorting issues

### ISSUE THREAD

**Issue by mattpottstj** [aurelia-ui-toolkits/aurelia-mdc-web#61]
Hi,

Couple of issues with data-tables sorting event and pagination needing to maintain the activePage property.
Also a couple of issues with focus events on the button and icon-button when disabled.

PR created for these fixes on Monday at: https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/pull/60

Sorry for creating an issue but didn't know how to alert you to review the PR. Doesn't appear to be any way to notify you even if I tagged you in the PR comment.

Would be good to get a method of contacting you (email or something) when i create PRs, especially for features I’m working on, as I don't want to pollute the Issues section.

Cheers,
Matt

**Comment by MaximBalaganskiy** [comment]
I'm on discord MaxB#8490
