### ISSUE TITLE
How to listen for mdc-switch "change" event?

### ISSUE THREAD

**Issue by green3g** [aurelia-ui-toolkits/aurelia-mdc-web#64]
Hello - is there any event dispatched from the mdc-switch component when the toggle happens? I have binding set up for `selected.bind` to bind to a value but I want to perform some logic after the toggle changes. 

I think this is what the API tab would show - however I'm not able to view the API page on this component:

![image](https://user-images.githubusercontent.com/5471079/150878587-e038d71c-03e0-46ac-a0c0-568541c8a277.png)

Happy to try and contribute a fix if you pointed me in the right direction I'm just not seeing where this information would be.

**Comment by MaximBalaganskiy** [comment]
`change` event
https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/blob/51f41b12f006f507225f2e7808ed7372fca71281/packages/switch/src/mdc-switch.ts#L55

Not all api tabs are complete unfortunately

**Comment by green3g** [comment]
Wow that was so obvious. Thanks!
