### ISSUE TITLE
Request for auto select single item on lookup

### ISSUE THREAD

**Issue by arjendeblok** [aurelia-ui-toolkits/aurelia-mdc-web#7]
When I type into the lookup associated input and there is only one item to select I still have to select it in the menu.

Is it an option to have an 'auto-select' option in the lookup component that automatically select an item when the lookup options (loadOptions) return only one value?

**Comment by MaximBalaganskiy** [comment]
You can set the value inside the options function, as a side effect. Would that work?

**Comment by arjendeblok** [comment]
I do not understand what you mean. And maybe you do not understand what I mean to.

If you look at the example and you type `Option 1` then you get a menu with only one option. I would be nice if this is automatically selected as the option and you do not have to click it.

**Comment by MaximBalaganskiy** [comment]
When you type your filter the options function gets called. Normally, that function just returns the array with one option in it but you can also set a value for example before returning the array.

**Comment by MaximBalaganskiy** [comment]
Is this still relevant?
