### ISSUE TITLE
mdc-segmented-button single doesn't work on Apple browsers

### ISSUE THREAD

**Issue by mreiche** [aurelia-ui-toolkits/aurelia-mdc-web#80]
I don't know exactly since when this bug occurs, but I've updated my phone recently to iOS 16 (16.0.2). And since then, the `mdc-segmented-button` in single mode doesn't work anymore as expected. I used the feature very often before.

To be more precise: The `checked.bind` doesn't change the bound variable.

After hours of investigating what's wrong in my code and searching for workarounds, I finally gave up and checked if the demo page behaves the same way (Aurelia MDC 9.0.1). And indeed, it does.

Initial state:
![IMG_0758](https://user-images.githubusercontent.com/572453/194423416-1e8540e3-2486-46d3-9c01-596e31c7ecf8.PNG)

After selecting `SEGMENT 2`:
![IMG_0759](https://user-images.githubusercontent.com/572453/194423466-5c882112-ddd0-4858-a073-be017d7d3269.PNG)

Expected behaviour:
`Segment1 - false, Segment2 - true`

Actual behavour:
`Segment1 - false, Segment2 - false`

The multiple mode works well.
Tested on Safari, DuckDuckGo and Brave browsers on the same device.

**Comment by MaximBalaganskiy** [comment]
Unfortunately, I don't have a Mac to debug this. Community help would be appreciated

**Comment by mreiche** [comment]
It also doesn't work in Desktop Safari (on Mac). I debugged that and the bug is located in the MDC component.
