### ISSUE TITLE
mdc-list-item non-interactive doesn't seem to work

### ISSUE THREAD

**Issue by KayvandenHeuvel** [aurelia-ui-toolkits/aurelia-mdc-web#86]
### Versions used:
aurelia-mdc-web 9.0.4
material-components-web 14.0.0

### Issue
The tag `<mdc-list-item non-interactive></mdc-list-item>`  does not seem to add the corresponding classes to the list item. Setting the class manually on the element won't work, so that's not a quick fix.
I used the non-interactive

**Comment by MaximBalaganskiy** [comment]
The feature got removed in MDC via https://github.com/material-components/material-components-web/pull/5880/commits/2553e86fee2753ec59f1fbc91764bf110ad9d3aa
