### ISSUE TITLE
hosting for au2 docs is dead

### ISSUE THREAD

**Issue by Zierk59** [aurelia-ui-toolkits/aurelia-mdc-web#89]
Hello, recently I tried to use bridge for au2 (8.0.2-au2) but there is lack of documentation or maybe there is no need to create new docs because it's compatible with v1, is it? 

URL of documentation (from README)
https://aurelia-mdc-web-au2.balaganskiy.pro/

**Comment by Zierk59** [comment]
Docs found here [https://github.com/aurelia-ui-toolkits/aurelia-mdc-web-au2-demo/tree/gh-pages](url) 
but there is set custom domain and redirect happens

**Comment by MaximBalaganskiy** [comment]
Fixed
