### ISSUE TITLE
[feature-request]: add the Tooltip component

### ISSUE THREAD

**Issue by glyad** [aurelia-ui-toolkits/aurelia-mdc-web#9]
Intention: 
- The component is must-have for real-world UI development;
- The component is implemented in base (original) MDC framework.

**Comment by MaximBalaganskiy** [comment]
Will add it once it's released in a stable version

**Comment by MaximBalaganskiy** [comment]
fixed by ba66efd452ab84e21cc296d44460a90fd501e7c5

**Comment by adriatic** [comment]
Max, I am impressed with your persistence and dedication to supporting "this ship" with so few passengers remaining. Let me know how are you doing

**Comment by MaximBalaganskiy** [comment]
@adriatic There are several ships in this fleet - Aurelia, MDC, and this bridge :) Which one did you have in mind?

**Comment by adriatic** [comment]
Primarily I meant the bridge as it seems that the first one built by @JeroenVinke and myself appeared eons ago. Not sure about MDC and even less about Aurelia as I have not touched it for years. When typing this last sentence, I said to myself "let's peek at https://aurelia.io" and discovered that the online documentation got improved a lot - and within a few seconds I discovered a bug 😄 .
