### ISSUE TITLE
documentation down

### ISSUE THREAD

**Issue by fabian-muff** [aurelia-ui-toolkits/aurelia-mdc-web#91]
Hello,
I am trying to use the v2 branch with my new aurelia2 project. I managed to setup the project. However, the links for the aurelia2 mdc documentation do not work. It is hard to use without documentation. For example, mdcmenu:selected.trigger="onMenuSelect($event.detail)" from the master branch seems not to work in the v2 version. 
Is there no documentation yet, or is the page down.
Best regards,
Fabian

**Comment by MaximBalaganskiy** [comment]
Fixed but changes have not propagated I think, the gh pages still redirect to the old domain. The event works, at least in the demo app. You can always start it locally - npm ci, npm start

**Comment by neptuniux** [comment]
Hi, 
Thank you for the work I greatly appreciate it.
Is the following url the official documentation page for Aurelia2-mdc-web ?
[https://aurelia-ui-toolkits.github.io/aurelia-mdc-web-au2-demo/#/](https://aurelia-ui-toolkits.github.io/aurelia-mdc-web-au2-demo/#/)
Best regards

**Comment by MaximBalaganskiy** [comment]
It is. Although in my browser it still redirects to the old domain. Incognito tab works though
