### ISSUE TITLE
Error: Cannot read properties of null (reading '$au')  -> in dialog via service... v2 branch

### ISSUE THREAD

**Issue by fabian-muff** [aurelia-ui-toolkits/aurelia-mdc-web#92]
Hello 

I stumbled upon a problem when trying to run an mdc-dialog via service. 
I implemented the example from packages/app/src/views/dialog/via-service from the v2 branch. However, I get an error when calling the dialog. Not sure what the problem is and if this is my fault or not. I implemented my code like in the example. To me it looks like the problem comes from "MdcDialogService.open"

![image](https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/assets/77620758/578bb3cf-4812-48dd-be70-e270cf4d7f31)

![image](https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/assets/77620758/83f2cec1-d52b-4fcc-bfcf-55e76b05eea9)

Any ideas?

**Comment by MaximBalaganskiy** [comment]
Have you registered your dialog control in aurelia?

**Comment by fabian-muff** [comment]
I registered only the whole aurelia-mdc library to test:

import { AllConfiguration } from '@aurelia-mdc-web/all';

Aurelia
  .register(AllConfiguration)
  .app(MyApp)
  .start();

Do I have to register the created "Service"?

**Comment by MaximBalaganskiy** [comment]
You dialog is an element and it needs to be registered with aurelia as a regular custom wlement

**Comment by fabian-muff** [comment]
okay, thank you very much!
