### ISSUE TITLE
Fresh installation issue

### ISSUE THREAD

**Issue by neptuniux** [aurelia-ui-toolkits/aurelia-mdc-web#93]
Hi,

I have trouble to install the last version of aurelia-mdc-web. I have followed the instructions in the "getting started" section of the documentation [(https://aurelia-ui-toolkits.github.io/aurelia-mdc-web-au2-demo/#/getting-started)](https://aurelia-ui-toolkits.github.io/aurelia-mdc-web-au2-demo/#/getting-started). I have changed the webpack configuration as required. 

I have this issue afterward:
```bash
AUR0014: Key cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?A common cause is circular dependency with bundler, did you accidentally introduce circular dependency into your module graph?
createMappedError@webpack-internal:///./node_modules/@aurelia/kernel/dist/esm/index.dev.mjs:155:49
validateKey@webpack-internal:///./node_modules/@aurelia/kernel/dist/esm/index.dev.mjs:1319:15
...
app@webpack-internal:///./node_modules/aurelia/dist/esm/index.dev.mjs:165:26
@webpack-internal:///./src/main.ts:12:6
./src/main.ts@http://localhost:9000/entry.bundle.js:3803:1
__webpack_require__@http://localhost:9000/entry.bundle.js:4166:32
@http://localhost:9000/entry.bundle.js:5236:56
@http://localhost:9000/entry.bundle.js:5238:12

WARNING in ./node_modules/@aurelia-mdc-web/segmented-button/dist/index.js 17:41-52
export 'IAttrMapper' (imported as 'IAttrMapper') was not found in '@aurelia/runtime-html' (possible exports: AdoptedStyleSheetsStyles, AppRoot,
...
 @ ./node_modules/@aurelia-mdc-web/all/dist/index.js 21:0-81 52:679-707
 @ ./src/main.ts 4:0-56 6:27-43
```

The main.ts is as follow:
```ts
import Aurelia from 'aurelia';
import { MyApp } from './my-app';
import { SVGAnalyzer } from '@aurelia/runtime-html';
import { AllConfiguration } from '@aurelia-mdc-web/all';

Aurelia
  .register(SVGAnalyzer,AllConfiguration)
  .app(MyApp)
  .start();
```

The version of the libraries are:
- Aurelia : 2.0.0-beta.20
- @aurelia-mdc-web/all: 9.2.1-au2
- @aurelia/router: 2.0.0-beta.20
- typescript: 5.5.4
- webpack: 5.93.0
- sass: 1.77.8
- sass-loader: 16.0.0

Everything works if I comment out the register part of the main.ts, so I guess the ploblem lies in the AllConfiguration or in an unsupported version of aurelia.

Do you have ideas where could be the problem and how to solve it ? 
Can you provide version of the libraries of a working project ?

Best regards,
Daniel

**Comment by MaximBalaganskiy** [comment]
The docs don't work well because of the high beta cadence. 
Try seeding with `npx makes aurelia-mdc-web/au2` instead which has pinned versions.
The au2 bridge works with beta.15 maximum at the moment due to changes to typescript decorators and general lack of time to upgrade.

Mind you, Google froze MDC web developments, both vanilla JS and web components. You might want to look for other alternatives,

**Comment by neptuniux** [comment]
Thank you for the prompt response,

The proposed solution works well. 

For those who want to look for somewhat similar components libraries that support aurelia (or at least without too much troubles), you have:
- [Fast Design](https://www.fast.design/)
- [Bootstrap](https://getbootstrap.com/)

Anyway thank you for the library, it was very useful.

**Comment by mreiche** [comment]
There exists an mdui integration for Aurelia 2: https://www.mdui.org/en/docs/2/frameworks/others#Aurelia

**Comment by MaximBalaganskiy** [comment]
Honestly, I've been burnt before by using "materialised" library, created by some random  guys which quickly lost interest in supporting it despite being paid. So... make your pick wisely :)

**Comment by MaximBalaganskiy** [comment]
FYI, I've updated the bridge and the starter project with the latest Aurelia versions

**Comment by mreiche** [comment]
> Honestly, I've been burnt before by using "materialised" library, created by some random guys which quickly lost interest in supporting it despite being paid. So... make your pick wisely :)

`mdui` seems to be feature complete. `material-web-components` were not.
