### ISSUE TITLE
aurelia-mdc-web with vite

### ISSUE THREAD

**Issue by fabian-muff** [aurelia-ui-toolkits/aurelia-mdc-web#95]
Hello

I used aurelia-mdc-web with aurelia 2 and webpack (branch v2).
However, since aurelia 2 uses now vite instead of webpack as default, I wonder if there is a way to use aurelia-mdc with vite. Has someone already tried. When I try it I get complaints about a missing plugin for .html imports in vite.

Best regards
Fabian

**Comment by MaximBalaganskiy** [comment]
I'm not familiar with vite set up but you have to have an loader config for html files in the bridge folder, similar to the loader for app html files

**Comment by MaximBalaganskiy** [comment]
The following config works for vite
```js
import { defineConfig } from 'vite';
import { nodePolyfills } from 'vite-plugin-node-polyfills'
import aurelia from '@aurelia/vite-plugin';

export default defineConfig({
  server: {
    open: !process.env.CI,
    port: 9000,
  },
  esbuild: {
    target: 'es2022'
  },
  optimizeDeps: {
    esbuildOptions: {
      loader: {
        '.html': 'text',
      },
    },
  },
  plugins: [
    aurelia({
      useDev: true,
    }),
    nodePolyfills()
  ]
});
```

**Comment by sowmichalla3** [comment]
Hello @MaximBalaganskiy, 

I've created a [skeleton app](https://github.com/gunakarchalla/Aurelia-2-Vite-MDC) using Vite and Aurelia MDC. I followed the instructions mentioned in the [URL](https://aurelia-ui-toolkits.github.io/aurelia-mdc-web-au2-demo/#/getting-started). I have incorporated the above config file too. But I am getting the following error:
`node_modules/aurelia/dist/esm/index.dev.mjs:4:531: ERROR: No matching export in "node_modules/@aurelia/runtime-html/dist/esm/index.dev.mjs" for import "Scope"`

Do you have any such basic app for reference, if no could you please let me know why am I getting this error?

Thank you in advance.

Regards,
Gunakar

**Comment by gunakarchalla** [comment]
Hello @MaximBalaganskiy,

I've created a [skeleton app](https://github.com/gunakarchalla/Aurelia-2-Vite-MDC) using Vite and Aurelia MDC. I followed the instructions mentioned in the [URL](https://aurelia-ui-toolkits.github.io/aurelia-mdc-web-au2-demo/#/getting-started). I have incorporated the above config file too. But I am getting the following error:
`node_modules/aurelia/dist/esm/index.dev.mjs:4:531: ERROR: No matching export in "node_modules/@aurelia/runtime-html/dist/esm/index.dev.mjs" for import "Scope"`
![Error Log](https://github.com/user-attachments/assets/2a4f53ef-ba62-4395-95e8-b7875aba151d)

Do you have any such basic app for reference, if no could you please let me know why am I getting this error?

Thank you in advance.

Regards,
Gunakar

**Comment by MaximBalaganskiy** [comment]
The bridge is using a specific beta version of au2, you need to match that. You also need to use include plugin property to enable html bundling in prod
